
/**
 * Change this link to your actual affiliate or offer URL
 */
export const SMART_LINK = "https://redirecting-kappa.vercel.app";

export const COUNTRIES = [
  // Tier 1 & Global High Traffic
  { code: 'US', name: 'USA', flag: '🇺🇸', phoneCode: '1' },
  { code: 'GB', name: 'UK', flag: '🇬🇧', phoneCode: '44' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', phoneCode: '1' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', phoneCode: '61' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', phoneCode: '49' },
  { code: 'FR', name: 'France', flag: '🇫🇷', phoneCode: '33' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', phoneCode: '34' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', phoneCode: '55' },
  { code: 'IN', name: 'India', flag: '🇮🇳', phoneCode: '91' },

  // Europe
  { code: 'IT', name: 'Italy', flag: '🇮🇹', phoneCode: '39' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', phoneCode: '31' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', phoneCode: '46' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', phoneCode: '47' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', phoneCode: '41' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', phoneCode: '48' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', phoneCode: '351' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', phoneCode: '30' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', phoneCode: '32' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', phoneCode: '43' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', phoneCode: '7' },

  // Asia & Oceania
  { code: 'JP', name: 'Japan', flag: '🇯🇵', phoneCode: '81' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', phoneCode: '82' },
  { code: 'CN', name: 'China', flag: '🇨🇳', phoneCode: '86' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', phoneCode: '62' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', phoneCode: '63' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', phoneCode: '66' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', phoneCode: '84' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', phoneCode: '92' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', phoneCode: '880' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', phoneCode: '60' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', phoneCode: '65' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', phoneCode: '64' },

  // Middle East
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', phoneCode: '90' },
  { code: 'AE', name: 'UAE', flag: '🇦🇪', phoneCode: '971' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', phoneCode: '966' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', phoneCode: '974' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', phoneCode: '972' },

  // South & Central America
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', phoneCode: '54' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', phoneCode: '57' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', phoneCode: '56' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', phoneCode: '51' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', phoneCode: '52' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', phoneCode: '598' },
  
  // African Countries
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phoneCode: '213' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', phoneCode: '244' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', phoneCode: '229' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', phoneCode: '267' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', phoneCode: '226' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', phoneCode: '257' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', phoneCode: '238' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', phoneCode: '237' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', phoneCode: '236' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', phoneCode: '235' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', phoneCode: '269' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', phoneCode: '242' },
  { code: 'CD', name: 'DR Congo', flag: '🇨🇩', phoneCode: '243' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', phoneCode: '253' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', phoneCode: '20' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', phoneCode: '240' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', phoneCode: '291' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', phoneCode: '268' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phoneCode: '251' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', phoneCode: '241' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', phoneCode: '220' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', phoneCode: '233' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', phoneCode: '224' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', phoneCode: '245' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', phoneCode: '225' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', phoneCode: '254' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', phoneCode: '266' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', phoneCode: '231' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', phoneCode: '218' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', phoneCode: '261' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', phoneCode: '265' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', phoneCode: '223' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', phoneCode: '222' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', phoneCode: '230' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', phoneCode: '212' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', phoneCode: '258' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', phoneCode: '264' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', phoneCode: '227' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phoneCode: '234' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phoneCode: '250' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', phoneCode: '239' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', phoneCode: '221' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', phoneCode: '248' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', phoneCode: '232' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', phoneCode: '252' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phoneCode: '27' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', phoneCode: '211' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', phoneCode: '249' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phoneCode: '255' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', phoneCode: '228' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phoneCode: '216' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', phoneCode: '256' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', phoneCode: '260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', phoneCode: '263' },
];

export const PREFERENCES = [
  { id: 'text', label: 'Text Chat', icon: 'fa-comments' },
  { id: 'video', label: 'Video Call', icon: 'fa-video' },
  { id: 'voice', label: 'Voice Note', icon: 'fa-microphone' },
];

export const SCAN_STEPS = [
  "Connecting to encrypted server...",
  "Scanning local area networks...",
  "Filtering active online profiles...",
  "Verifying connection status...",
  "Optimizing for your preferences...",
  "Match found! Fetching details...",
];

export const NAMES = [
  "Sarah J.", "Emily W.", "Jessica M.", "Chloe R.", "Madison K.", "Ashley B.", "Lauren T.", "Megan D.", "Hannah L.",
  "Ayesha K.", "Svetlana P.", "Maria G.", "Fatima Z.", "Priya S.", "Amara O.", "Nia K.", "Zoe H.",
  "Olivia S.", "Emma B.", "Ava L.", "Charlotte J.", "Sophia M.", "Isabella K.", "Mia G.", "Amelia F.", "Evelyn D.", "Abigail T.",
  "Luna W.", "Ella H.", "Elizabeth R.", "Sofia V.", "Scarlett C.", "Elena B.", "Layla G.", "Willow F.",
  "Alice M.", "Ivy T.", "Florence K.", "Grace L.", "Maya J.", "Aria D.", "Rose W.", "Lily B.", "Violet R.", "Aurora C.",
  "Penelope G.", "Eleanor S.", "Hazel K.", "Lucy M.", "Stella P.", "Nova L.", "Zoey B.", "Mila T.", "Chloe F.",
  "Elena R.", "Sarah M.", "Victoria S.", "Grace P.", "Nora L.", "Camila K.", "Eliana B.", "Hazel D.", "Aria F.", "Mila G.",
  "Aurora S.", "Penelope M.", "Layla P.", "Elizabeth W.", "Scarlett L.", "Nova K.", "Mia R.", "Charlotte T.", "Emma P.", "Olivia F.",
  "Isabella B.", "Sophia G.", "Amelia L.", "Evelyn K.", "Abigail M.", "Luna R.", "Ella D.", "Sofia T.", 
  "Elena G.", "Sarah L.", "Victoria M.", "Grace S.", "Nora P.", "Camila W.", "Eliana L.", "Hazel R.", "Aria T.", "Mila J.",
  "Aurora G.", "Penelope L.", "Layla M.", "Elizabeth S.", "Scarlett P.", "Nova W.", "Mia L.", "Charlotte R.", "Emma T.", "Olivia J.",
  "Isabella G.", "Sophia L.", "Amelia M.", "Evelyn S.", "Abigail P.", "Luna L.", "Ella R.", "Sofia T.",
  "Adriana C.", "Alba G.", "Alessia M.", "Alexandra S.", "Alma B.", "Amanda F.", "Ana P.", "Anabela L.", "Anastasia K.", "Andrea R.",
  "Angela T.", "Angelina D.", "Anita G.", "Anna M.", "Antonia S.", "Ariana B.", "Artemis L.", "Astrid F.", "Audrey K.", "Aura D.",
  "Beatriz C.", "Bella G.", "Bianca M.", "Bonnie S.", "Brenda B.", "Brianna F.", "Brigitte L.", "Brittany K.", "Bruna R.", "Caitlin T.",
  "Callie D.", "Carina G.", "Carla M.", "Carmen S.", "Carol B.", "Carolina F.", "Cassandra L.", "Catalina K.", "Catherine R.", "Cecilia T.",
  "Celeste D.", "Celia G.", "Chantal M.", "Charis S.", "Chelsea B.", "Chiara F.", "Cindy L.", "Clara K.", "Clarissa R.", "Claudia T.",
  "Cleo D.", "Colette G.", "Constance M.", "Cora S.", "Corinne B.", "Cristina F.", "Cynthia L.", "Dagmar K.", "Dahlia R.", "Daisy T.",
  "Dana D.", "Daniella G.", "Daphne M.", "Daria S.", "Deborah B.", "Delphine F.", "Denise L.", "Desiree K.", "Diana R.", "Dora T.",
  "Doris D.", "Dorothy G.", "Edith M.", "Eileen S.", "Elaine B.", "Eleonora F.", "Elif L.", "Elisa K.", "Elisabeth R.", "Elise T.",
  "Eliza D.", "Elke G.", "Ellen M.", "Eloise S.", "Elsa B.", "Elvira F.", "Emanuela L.", "Emilia K.", "Emmanuelle R.", "Ena T.",
  "Enrica D.", "Erica G.", "Erika M.", "Esme S.", "Estelle B.", "Ester F.", "Esther L.", "Eugenia K.", "Eunice R.", "Eva T.",
  "Evangeline D.", "Eve G.", "Evelina M.", "Fabiana S.", "Faith B.", "Fanny F.", "Farrah L.", "Fatoumata K.", "Faustine R.", "Fay T.",
  "Federica D.", "Felicia G.", "Fernanda M.", "Filippa S.", "Fiona B.", "Flavia F.", "Flora L.", "Franca K.", "Francesca R.", "Freya T.",
  "Frida D.", "Gabriela G.", "Gaia M.", "Gemma S.", "Genevieve B.", "Georgia F.", "Geraldine L.", "Gisela K.", "Giselle R.", "Giulia T.",
  "Gladys D.", "Gloria G.", "Greta M.", "Gudrun S.", "Guinevere B.", "Gwen F.", "Haley L.", "Hanna K.", "Harriet R.", "Heidi T.",
  "Helen D.", "Helena G.", "Helga M.", "Hester S.", "Hilda B.", "Holly F.", "Hope L.", "Ida K.", "Ilona R.", "Imani T.",
  "Imogen D.", "Ines G.", "Ingrid M.", "Irene S.", "Iris B.", "Irma F.", "Isabel L.", "Isadora K.", "Isis R.", "Ivana T.",
  "Jacqueline D.", "Jade G.", "Jana M.", "Jane S.", "Janine B.", "Jasmine F.", "Jean L.", "Jemima K.", "Jennifer R.", "Jenny T.",
  "Jocelyn D.", "Joelle G.", "Johanna M.", "Jolene S.", "Josephine B.", "Joy F.", "Judith L.", "Julia K.", "Juliana R.", "Julie T.",
  "Justine D.", "Kaitlyn G.", "Kara M.", "Karen S.", "Karina B.", "Karla F.", "Katarina L.", "Katherine K.", "Kathleen R.", "Katrina T.",
  "Kaya D.", "Keira G.", "Kelly M.", "Kendra S.", "Kiki B.", "Kim F.", "Kira L.", "Kirsten K.", "Klara R.", "Krista T.",
  "Lana D.", "Lara G.", "Larissa M.", "Laura S.", "Lea B.", "Leila F.", "Lena L.", "Leona K.", "Leonor R.", "Letizia T.",
  "Lexi D.", "Lia G.", "Liana M.", "Lidia S.", "Liesel B.", "Lila F.", "Lillian L.", "Lina K.", "Linda R.", "Lisa T.",
  "Livia D.", "Lola G.", "Lorena M.", "Lori S.", "Lotte B.", "Louisa F.", "Lourdes L.", "Lucia K.", "Lucille R.", "Ludovica T.",
  "Luisa D.", "Lulu G.", "Lydia M.", "Lynne S.", "Mabel B.", "Madeleine F.", "Maeve L.", "Magdalena K.", "Maggy R.", "Maia T.",
  "Maira D.", "Malika G.", "Manon M.", "Manuela S.", "Mara B.", "Marcella F.", "Margaret L.", "Margarita K.", "Margot R.", "Mari T.",
  "Maria D.", "Mariam G.", "Marianne M.", "Maribel S.", "Marie B.", "Mariela F.", "Marilyn L.", "Marina K.", "Marion R.", "Marisa T.",
  "Marisol D.", "Marta G.", "Martina M.", "Mary S.", "Matilda B.", "Maude F.", "Maureen L.", "Mavis K.", "Maxine R.", "May T.",
  "Melanie D.", "Melina G.", "Melinda M.", "Melissa S.", "Melody B.", "Mercedes F.", "Mia L.", "Michaela K.", "Michelle R.", "Mina T.",
  "Mira D.", "Miranda G.", "Miriam M.", "Moira S.", "Molly B.", "Monica F.", "Monique L.", "Morgan K.", "Muriel R.", "Myra T.",
  "Nadia D.", "Nadine G.", "Nancy M.", "Naomi S.", "Natalia B.", "Natalie F.", "Natascha L.", "Nia K.", "Nicole R.", "Nika T.",
  "Nina D.", "Noemi G.", "Nora M.", "Norma S.", "Odette B.", "Olga F.", "Olive L.", "Olivia K.", "Oona R.", "Ophelia T.",
  "Orla D.", "Ottilie G.", "Pamela M.", "Paola S.", "Patricia B.", "Paula F.", "Paulina L.", "Phoebe K.", "Phyllis R.", "Pia T.",
  "Priscilla D.", "Prudence G.", "Rachel S.", "Ramona B.", "Raquel F.", "Rebecca L.", "Regina K.", "Renata R.", "Renee T.",
  "Ria D.", "Rita G.", "Roberta M.", "Rochelle S.", "Romy B.", "Rosa F.", "Rosalie L.", "Rosalind K.", "Rosamund R.", "Rosanna T.",
  "Rosemary D.", "Rosie G.", "Rowena M.", "Ruby S.", "Ruth B.", "Sabina F.", "Sabine L.", "Sabrina K.", "Sacha R.", "Sade T.",
  "Saffron D.", "Sally G.", "Salma M.", "Samantha S.", "Samira B.", "Sandra F.", "Sania L.", "Sanya K.", "Saphira R.", "Sasha T.",
  "Saskia D.", "Sayan G.", "Selena M.", "Selina S.", "Selma B.", "Seraphina F.", "Serena L.", "Shakira K.", "Shana R.", "Shania T.",
  "Shari D.", "Sharon G.", "Sheila M.", "Shelby S.", "Shirley B.", "Shona F.", "Sia L.", "Sibyl K.", "Sienna R.", "Sigrid T.",
  "Silke D.", "Silvana G.", "Silvia M.", "Simona S.", "Simone B.", "Sina F.", "Siobhan L.", "Siri K.", "Sonia R.", "Sonja T.",
  "Soraya D.", "Stacy G.", "Stefanie M.", "Stela S.", "Stephanie B.", "Suki F.", "Susan L.", "Susanna K.", "Susie R.", "Suzanne T.",
  "Svetlana D.", "Sybil G.", "Sydnee M.", "Sylvia S.", "Tabitha B.", "Talia F.", "Tamara L.", "Tania K.", "Tanita R.", "Tanya T.",
  "Tara D.", "Taryn G.", "Tatiana M.", "Tea B.", "Teresa F.", "Tess L.", "Tessa K.", "Thais R.", "Thea T.",
  "Thelma D.", "Theodora G.", "Theresa M.", "Tiana S.", "Tiffany B.", "Tilda F.", "Tina L.", "Tiziana K.", "Tracey R.", "Tricia T.",
  "Trina D.", "Trudy G.", "Ula M.", "Ulrike S.", "Uma B.", "Ursula F.", "Ute L.", "Valentina K.", "Valeria R.", "Valerie T.",
  "Vanessa D.", "Vania G.", "Vera M.", "Verena S.", "Veronica B.", "Vicki F.", "Vicky L.", "Victoria K.", "Vida R.", "Viola T.",
  "Virginia D.", "Vivian G.", "Viviana M.", "Vivienne S.", "Wallis B.", "Wanda F.", "Wendy L.", "Whitney K.", "Wilma R.", "Winnie T.",
  "Xandra D.", "Xenia G.", "Yara M.", "Yasmin S.", "Yolanda B.", "Yvonne F.", "Zara L.", "Zelda K.", "Zina R.", "Zita T.",
  "Zoe D.", "Zofia G.", "Zora M.", "Zoya S.", "Zula B.", "Zuleika F.", "Zuri L."
];

export const AVATAR_URLS = [
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAFzSk3abjntk8lLi0kjNQogvnQ2m3wPHwkg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV3SWOn_WeScRw5SaTH4w1bbt4mHR3rU6oog&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZyhiT9niTht9TC8e46qJ1trPC2Bcs0AUlw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4Q556HusGUTiGRRXcf_c0ZoeB4HSpDwN8LCpUZ_JfaSVPLt4No8zCPmA7&s=10',            
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXEnK_56NHPb-N2xrmxGuW7ItXcPdcfkFRKg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNo8M_xbvVlfh4lQVgPuNTERMlO_lEppFoSw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr9OjJ5dxgP87BeZ9Q-Xin-YX-ajcX0y5-TQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRDhW0bOCN8rhLk-S8GWos-t_hvJtBXERx_g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDOaSqA15oVoFDdknObWAe-DvJioiPlWTXwA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScrwP0RwusUPCfP9vLaRn9786KkApGDx4IoYeChim0TzLU9Bv2K-O_FRA_&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQATvMP0NSmhH97zUTuqzkXipcF4iq21XVwkpbIRjTlDyNRZPSOMI7j88H6&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSEpUGnNG8I4Qzhtlj3kWxeGJAVOmdVPexMA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiAsaFdwiJDUqs7VPkCaYRC9jJ8LkYg3B3LCA22flcz7jT0xlwGr-Zrxs&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSg7Ws2CSlr5wYbkBHO8NTdk4jwF3PdpNhJxZvbeHz3TdpqfN6MmROxCR9&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOfnXlV43KA6OSplW8FJ4R0WTFSiYTTfc-Dw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVOeLKLzHpbtRfS1iR-NliM4guejZhSsDxXg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0hNh3Lk1__XSSdGSy1pSHHS3-Zmd_H7yu-g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfgzvbiXFO99Y_FNRjx6VztudI0kIONLheNA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-DBoVonB4NnwMvH41kguVGCr4UQXhvMG1g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8dETkzoRQsrMLiAsvZ8GAX7aD_0Z3P51fCQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtcIoih5hd7zWskNsdlc1KcnJfOqiWiMJMww&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-TS9NXnYcUyFrOjxUsZETUIGH6TxeLqbl7LPkA6SlBwNOQ0v6zUDRvxM&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6r52J-OFBc2r5sh-Nybm1f7C_eL1t_XsV2Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFypp9unvUigLqVEKedNYml9dxr1g2FtKnBw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvOI2nl2jHn0tBWS1e33y4IOvYJ7nUAX8uZw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKVhN2N9IhpNXnE6vk3XIHe37-Y4-HNO0L0Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8mU441TfMGxh7uycTm7UjQCqHv4j1SCydxw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE4q-0XTafAIJNa1fOz9rSX8f2fEQd6RJQKw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF4oYLt8XzQXLKyKMD41CfcN1FpdxYXv52wA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfoBJ1R5MRQFiSmfmxxfyMefmo8AK7MYFtLQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaIoeRwD_tmn7kO9yElyHQaoEdEoMHLsrZRg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwL8XSvt9A5jvQqhS3eHmXTam37EpGp4klLg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIHLt61ExFzrzjJOwLrFcCokYOh_eRKjhwyw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2hctqh5I3SYC-hRqvpAVgYiMXb3eXLPK98Q&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwwyLsl0_3F6Thtjr8ayATF8UhDYhIhgaJsQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpLVwnVovHPuOownytsSCVQKN9ifif8xJz_g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzAlDPy5mbEPwg8h1C0oAocDiXSsa8zDZX4w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6SPYWs0AyoIvxQX_p_b4yqB2SIKiPrko4tg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_jOx44eEAD_R4U9SwgdlSTE135s3GFdIs1w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoPtx8cVmCavahCzbnHThcme1NDdqYLAN1aA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-KEY2HXWv0H4HFJwLQNIByu6eNjYHTJp3iA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFHZqDDo9U-gSF4qfwrFWRSwpXkAS0tszpXQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTljh2QWrLo9KY5vaO79w6xmUpAZZ29U1RcNg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7rZyIA1FFcCZtYd-T92FOQZ0Vm4XgCEdWCA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1P2fYUUbG4cWPJx801BYZVONTrdVqyzX57A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTcKflNf7DzN4WNYphn1uIupIDFxgtDShu0w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Sac5yCvP28f-hjsjxw-HIhkfe21nXCjFRw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWO_BNbiROx6zcWdpnj7TT3aWCbNKnigfBXw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJlbFvF_I5eP0hMnJQo3VJgF1CHo0M4adxeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQcQTQtBf_0mC-5cH8ApSQXR2XVcXW3EeZdw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_Igd_sAw8GulyHl8NCnDL41OvcPLIa0kHHw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRj-xutjHGMAnNUi_vvrLxn4f9oVpR-k6vWA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4fkfkb9xVzedgBuIFoNThM4rJ-1Vda-7j5Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCERd7D4hNCgFL29iAihvvpKWLh4Gmu35kdQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0VQf8oMaTShZTNS7HGCdQH8W-QcL9bxrJJg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdaYZ1Dn1SXWYfEXS_BPaqkh-aV7bx3UFkig&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSoRx9N7j0flwFMwB1Fch5x0s_WOxrh2AMINw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Udcbb4xsAhaLfjSDT24m2vkeEZyn8XLs7A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQdNX_rUkvo7Cg67441WW7ifAI4bRzYgPLsA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMQEgmqCq3-XI5UTQLauwiyK-Z8J-VVYoOgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTShyj7xOYwxa-qrp1Z4MxVqTkXk5faLZpsCw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcCL9njdTwbpAZjAu_BKPhzEbFdLQWeAlQ0Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQKbviKFo8-U13A4RVRdYOi2yCEHMe0nVPIg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgnAVIc2Qyqh9jC3Rl2tZax6NLE3FApskZPQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo50SY967Qc2ZWq-a6u902XeB2kO55VGQAIA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYvf8fqa0wTAOj4VRGzZVg_qk8ZGGjU13pOQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYoEbWHDm29LFyQGMUicW4ZKeVhbifj7IldA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdWlHHPJ78Lb2tW29iZel5Cj7SRUCYjG_dOQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkuT_ux-tsRBUocYrdk3MDhSmpXyofjy9MgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK_v3GWkgvcJO_4k2rJc4kWOKJI2HLwTGZbA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRrI3AL4lVk5gKonBIrztEPhQpTjcPn5ZdAQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8iKgtJNV063nb8wG6hLqMaFqxTIpf01_g-g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzC6LEmumQaFtUYGWkk9b3g-UcCY8jfELugg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyBHGTq7J6Er7E6taiJHaz6FID-8ryhBPc7g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4R5KDEosC0c1pl-rN6_ATI_5qsq8xSjhZkw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4XecPwp0qb_uOFiKzyYxJuO4_QfynFtMNA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVVgfeG79S7WwGTO3WXzcJ2j_amrXkHykcRA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBJZ4Bt0qxNIvzk6MNQnTyTEhf6FlLDALSuQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjz9ombGj6JuXK44wbX3A2j1dSwMSAuXqkTw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkt0AyZgwSNVgyMRf9pAj-n5H68mQrgKEEvA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThrD-WpoqqGJc1Bjfi09YG4ASKHIQIHWA-WQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwB7HWaB1whZ9OwjMPPydpzFyx0dOLgbH82w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6bM55vXTt5zL7T7oWqH8UgQTF4qkzBERH-w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZMn1XeDgufVYJag0m1ScKyGvhZ-6VWlB4hA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJV3LrFkMhq69vJV8odiOJiKfm92RwO_kAOA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRovxdohY2NeB43U4u5yRj5RX67RKQd-PGgeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwDKmcso9ivQJhHAxJkQ90PfO6k8-E-Unz3A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPVWMdtX-WTsglvqyvxpdd_ncO6dZHKPhfWQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShZyvTIk_wX-RyFqVq6PsCVvQ43DzDg1gF0g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS18rjV61pf-Kkw93P8fo_GMD9Idv57BgQegA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVwk28fGpCeiOnU_v4gM_xmmutlD4TdTaJNIBnnakQuc9oBcMJBSFomlvD&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSF3B1t8IKJ8SackXZ34Ul844J8t89K_fraw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqt2QSj2E9P9E8qneWPqKN-Y9sTrRgFqgLeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXGH0eM6A3qIBu1SoHO2WKLiYXCVits4u_Wg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY0nVbVAyDMiNgAOJSyFMdr9JgXP6u-tnRjg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPri27yFhlF-MAVeozZ00A-tp5r8oH4QZLQA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZtN2Z8Y0VCub7HXy1a1FNbkwA632bWbfQQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUgddTyJCjtmFXq-XYPADnuA_j2bhPr-iCFw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOzgVzG-UrcWB6i_pXRDZetIab4RVeGY6LfQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRig5Z4r9Na7WtvWMcPhMRWO-vxYITQxnGTEA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQBmNSSTyzY6qNUNXh3PWEO2voLlLDTFW6RA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPWtvsoXkUSxr4FhGEWif36fdhmQ3WYrsaSA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGJdpCFIUFCozbAI1zxuOH8bdgzQ27mcg-zg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQah1H61b5BChnJoZkzH1VZ2ODQvOmYTMY71w&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEyWdR9JghLDjF8H1pjyQ1SrvpI7hMQD0jQA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUL6JxEUMLF9vvB2wq2-_VKmvUw1-eR3J49B4tiQBrj4tVz-_plQvabbE&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxFC7MTgJs5HxeKj5p-mCyMnIeoWx-PF8xV4buXfXiQwZ92G2fzioZicb1&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwRg4fw_NWyiGZcR8exPyuNNZLC5LspVCbQg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHhdSh1nBKZS8-Atw5Z6x4C4FrbAi5sC0Seg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQht92k0FECMx5KzD-8ry_UbRrXki2hAx2GZWxTnPwJGd1R8beor7qCFsua&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7Mjaz0O_EaQKNImm9POuvfhgpgACKgbHX5A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfHc9wIUpAZ6tGgHcuh7uMgSE73e3MiXrpIw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSwa4h6ctjlKYAuYjTJg7apT7yFzeclZBCVw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLVSo425yfuohV1wofyHOHfSqGSqviMo3Ung&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSO6Bq9udLzcwFq-bJmd2B9Cq6oL9hMkZMuQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfMKZ1a1QxAhFHKbrcJTpbDX_qjWzlGbi5Rg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5So9rXG6_eILhT0bkgTqmiqo0Aa1kIGVr1g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTczEUa2QtS5CvjAc9HFeZovoCLgtI1-Y5pYw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLZVsw3fF0MAcrvGRcjrocEyV3_cLkTVjZwA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeNWUV_8MU3wINXnyYHfrvEcYG-L-EYEraRw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfa6rq74f35M30YTaKz0OUrCcIrTS5eCC_tg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7J6K9NBmnl8oEF8zMIy3mOwH4_xutpGAgKQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuSff_LbXojRUX_oE7waI3d3-QualApp3T7w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXdfy8AVTJV2b4BQ4xisLXBpyeGu1oScXmg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScZS26U1UGiE2TlPDKUHLisbG4PJlyHg_jog&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnBczfXO7TJB2g9PXBFLz2wy69FOuh5mV7pg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSpWc12uRczAUU_zorKo-zqLhEeZDJITSmbA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd9g4q6i8P29p9OF89IpJYDXFWxnUfT5nNgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdeAXps2kgZGRgeulyGuYSEyLxLU44eFEUeg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5PMHi_5Kl3X2ucjuo7D0KafekF10godIfMg&usqp=CAU'
];
