
/**
 * Change this link to your actual affiliate or offer URL
 */
export const SMART_LINK = "https://shorteroverflowmartyr.com/pfvvfhsid?key=ce13e817b2b71b3f25bfb988c80c2f46";

export const COUNTRIES = [
  // Global High Traffic
  { code: 'US', name: 'USA', flag: '🇺🇸', phoneCode: '1', city: 'New York' },
  { code: 'GB', name: 'UK', flag: '🇬🇧', phoneCode: '44', city: 'London' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', phoneCode: '1', city: 'Toronto' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', phoneCode: '61', city: 'Sydney' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', phoneCode: '49', city: 'Berlin' },
  { code: 'FR', name: 'France', flag: '🇫🇷', phoneCode: '33', city: 'Paris' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', phoneCode: '55', city: 'São Paulo' },
  { code: 'IN', name: 'India', flag: '🇮🇳', phoneCode: '91', city: 'Mumbai' },

  // African Nations
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phoneCode: '213', city: 'Algiers' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', phoneCode: '244', city: 'Luanda' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', phoneCode: '229', city: 'Porto-Novo' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', phoneCode: '267', city: 'Gaborone' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', phoneCode: '226', city: 'Ouagadougou' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', phoneCode: '257', city: 'Bujumbura' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', phoneCode: '238', city: 'Praia' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', phoneCode: '237', city: 'Yaoundé' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', phoneCode: '236', city: 'Bangui' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', phoneCode: '235', city: "N'Djamena" },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', phoneCode: '269', city: 'Moroni' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', phoneCode: '242', city: 'Brazzaville' },
  { code: 'CD', name: 'Congo (DRC)', flag: '🇨🇩', phoneCode: '243', city: 'Kinshasa' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', phoneCode: '253', city: 'Djibouti' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', phoneCode: '20', city: 'Cairo' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', phoneCode: '240', city: 'Malabo' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', phoneCode: '291', city: 'Asmara' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', phoneCode: '268', city: 'Mbabane' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phoneCode: '251', city: 'Addis Ababa' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', phoneCode: '241', city: 'Libreville' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', phoneCode: '220', city: 'Banjul' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', phoneCode: '233', city: 'Accra' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', phoneCode: '224', city: 'Conakry' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', phoneCode: '245', city: 'Bissau' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', phoneCode: '225', city: 'Abidjan' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', phoneCode: '254', city: 'Nairobi' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', phoneCode: '266', city: 'Maseru' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', phoneCode: '231', city: 'Monrovia' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', phoneCode: '218', city: 'Tripoli' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', phoneCode: '261', city: 'Antananarivo' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', phoneCode: '265', city: 'Lilongwe' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', phoneCode: '223', city: 'Bamako' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', phoneCode: '222', city: 'Nouakchott' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', phoneCode: '230', city: 'Port Louis' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', phoneCode: '212', city: 'Casablanca' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', phoneCode: '258', city: 'Maputo' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', phoneCode: '264', city: 'Windhoek' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', phoneCode: '227', city: 'Niamey' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phoneCode: '234', city: 'Lagos' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phoneCode: '250', city: 'Kigali' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', phoneCode: '239', city: 'São Tomé' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', phoneCode: '221', city: 'Dakar' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', phoneCode: '248', city: 'Victoria' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', phoneCode: '232', city: 'Freetown' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', phoneCode: '252', city: 'Mogadishu' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phoneCode: '27', city: 'Johannesburg' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', phoneCode: '211', city: 'Juba' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', phoneCode: '249', city: 'Khartoum' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phoneCode: '255', city: 'Dar es Salaam' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', phoneCode: '228', city: 'Lomé' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phoneCode: '216', city: 'Tunis' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', phoneCode: '256', city: 'Kampala' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', phoneCode: '260', city: 'Lusaka' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', phoneCode: '263', city: 'Harare' },
];

export const PREFERENCES = [
  { id: 'text', label: 'Text Chat', icon: 'fa-comments' },
  { id: 'video', label: 'Video Call', icon: 'fa-video' },
  { id: 'voice', label: 'Voice Note', icon: 'fa-microphone' },
];

export const SCAN_STEPS = [
  "Connecting to encrypted server...",
  "Scanning local area networks...",
  "Filtering active online profiles...",
  "Verifying connection status...",
  "Optimizing for your preferences...",
  "Match found! Fetching details...",
];

export const NAMES = [
  "Sarah J.", "Emily W.", "Jessica M.", "Chloe R.", "Madison K.", "Ashley B.", "Lauren T.", "Megan D.", "Hannah L.",
  "Olivia S.", "Emma B.", "Ava L.", "Charlotte J.", "Sophia M.", "Isabella K.", "Mia G.", "Amelia F.", "Evelyn D.",
  "Abigail H.", "Harper P.", "Luna V.", "Ella Z.", "Sofia C.", "Avery Q.", "Scarlett X.", "Victoria R.", "Grace N.",
  "Camila T.", "Bella B.", "Aurora S.", "Savannah G.", "Audrey F.", "Brooklyn K.", "Claire J.", "Skylar L.", "Lucy M.",
  "Paisley P.", "Everly D.", "Anna W.", "Caroline S.", "Nova O.", "Genesis G.", "Emilia E.", "Kennedy K.", "Maya M.",
  "Amara", "Zahara", "Fatima", "Aisha", "Chioma", "Zuri", "Nala", "Imani", "Lindiwe", "Zena", "Khadija", "Nia",
  "Elena", "Valentina", "Martina", "Sofia", "Lucia", "Camila", "Mariana", "Antonella", "Renata", "Isadora",
  "Priya", "Ananya", "Ishani", "Saanvi", "Aavya", "Kyra", "Zara", "Yuki", "Mei", "Hana", "Sakura", "Ji-Woo"
];

export const PROFILE_STATUSES = [
  "Looking for someone to talk to ✨",
  "Available for video call now!",
  "Just joined, say hi!",
  "Feeling lonely tonight... 🥺",
  "Want to chat about anything?",
  "Bored at home, let's connect!",
  "New in town, looking for friends!",
  "Active and ready to chat 💬",
  "Thinking about you... let's talk? 😉",
  "Ready for some late night secrets? 🌙",
  "Is it hot in here or is it just our connection? 🔥",
  "Can you handle a private chat? 😈",
  "Just got out of the shower, let's chat! 🚿",
  "Feeling a bit naughty tonight, want to talk? 🌹",
  "Let's turn this chat into something more... 🥂",
  "Sweet or spicy? Tell me in chat! 🌶️",
  "Waiting for your first message. Don't be shy! 😘",
  "Late night vibes only. DM me... 🎧",
  "Searching for a partner in crime... 🕵️‍♀️",
  "Can't sleep, need some company... ✨"
];

export const RECENT_ACTIVITY_NAMES = [
  "Alex", "Jordan", "Mike", "Sophie", "Chris", "Emma", "Daniel", "Luisa", "Marco", "Priya", "Chen", "Yuki", "Ahmed"
];

export const AVATAR_URLS = [
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAFzSk3abjntk8lLi0kjNQogvnQ2m3wPHwkg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV3SWOn_WeScRw5SaTH4w1bbt4mHR3rU6oog&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZyhiT9niTht9TC8e46qJ1trPC2Bcs0AUlw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4Q556HusGUTiGRRXcf_c0ZoeB4HSpDwN8LCpUZ_JfaSVPLt4No8zCPmA7&s=10',            
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXEnK_56NHPb-N2xrmxGuW7ItXcPdcfkFRKg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNo8M_xbvVlfh4lQVgPuNTERMlO_lEppFoSw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr9OjJ5dxgP87BeZ9Q-Xin-YX-ajcX0y5-TQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRDhW0bOCN8rhLk-S8GWos-t_hvJtBXERx_g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDOaSqA15oVoFDdknObWAe-DvJioiPlWTXwA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScrwP0RwusUPCfP9vLaRn9786KkApGDx4IoYeChim0TzLU9Bv2K-O_FRA_&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQATvMP0NSmhH97zUTuqzkXipcF4iq21XVwkpbIRjTlDyNRZPSOMI7j88H6&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSEpUGnNG8I4Qzhtlj3kWxeGJAVOmdVPexMA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiAsaFdwiJDUqs7VPkCaYRC9jJ8LkYg3B3LCA22flcz7jT0xlwGr-Zrxs&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSg7Ws2CSlr5wYbkBHO8NTdk4jwF3PdpNhJxZvbeHz3TdpqfN6MmROxCR9&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOfnXlV43KA6OSplW8FJ4R0WTFSiYTTfc-Dw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVOeLKLzHpbtRfS1iR-NliM4guejZhSsDxXg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0hNh3Lk1__XSSdGSy1pSHHS3-Zmd_H7yu-g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfgzvbiXFO99Y_FNRjx6VztudI0kIONLheNA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-DBoVonB4NnwMvH41kguVGCr4UQXhvMG1g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8dETkzoRQsrMLiAsvZ8GAX7aD_0Z3P51fCQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtcIoih5hd7zWskNsdlc1KcnJfOqiWiMJMww&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-TS9NXnYcUyFrOjxUsZETUIGH6TxeLqbl7LPkA6SlBwNOQ0v6zUDRvxM&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6r52J-OFBc2r5sh-Nybm1f7C_eL1t_XsV2Q&usqp=CAU',
  'https://lh3.googleusercontent.com/proxy/PkO3rDNJ45xahRWcikpAUWaZrWxfqZtoeHh_Wt5ivmnRhrrodJD5xfCWlCnhH0NOvR1wP_-NfzDEEpUbluUW278gQvxp7Z48UQfEKBOPE5T-_A',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFypp9unvUigLqVEKedNYml9dxr1g2FtKnBw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvOI2nl2jHn0tBWS1e33y4IOvYJ7nUAX8uZw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKVhN2N9IhpNXnE6vk3XIHe37-Y4-HNO0L0Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8mU441TfMGxh7uycTm7UjQCqHv4j1SCydxw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE4q-0XTafAIJNa1fOz9rSX8f2fEQd6RJQKw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF4oYLt8XzQXLKyKMD41CfcN1FpdxYXv52wA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfoBJ1R5MRQFiSmfmxxfyMefmo8AK7MYFtLQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaIoeRwD_tmn7kO9yElyHQaoEdEoMHLsrZRg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwL8XSvt9A5jvQqhS3eHmXTam37EpGp4klLg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIHLt61ExFzrzjJOwLrFcCokYOh_eRKjhwyw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2hctqh5I3SYC-hRqvpAVgYiMXb3eXLPK98Q&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwwyLsl0_3F6Thtjr8ayATF8UhDYhIhgaJsQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpLVwnVovHPuOownytsSCVQKN9ifif8xJz_g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzAlDPy5mbEPwg8h1C0oAocDiXSsa8zDZX4w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6SPYWs0AyoIvxQX_p_b4yqB2SIKiPrko4tg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_jOx44eEAD_R4U9SwgdlSTE135s3GFdIs1w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoPtx8cVmCavahCzbnHThcme1NDdqYLAN1aA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-KEY2HXWv0H4HFJwLQNIByu6eNjYHTJp3iA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFHZqDDo9U-gSF4qfwrFWRSwpXkAS0tszpXQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTljh2QWrLo9KY5vaO79w6xmUpAZZ29U1RcNg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7rZyIA1FFcCZtYd-T92FOQZ0Vm4XgCEdWCA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1P2fYUUbG4cWPJx801BYZVONTrdVqyzX57A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTcKflNf7DzN4WNYphn1uIupIDFxgtDShu0w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Sac5yCvP28f-hjsjxw-HIhkfe21nXCjFRw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWO_BNbiROx6zcWdpnj7TT3aWCbNKnigfBXw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJlbFvF_I5eP0hMnJQo3VJgF1CHo0M4adxeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQcQTQtBf_0mC-5cH8ApSQXR2XVcXW3EeZdw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_Igd_sAw8GulyHl8NCnDL41OvcPLIa0kHHw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRj-xutjHGMAnNUi_vvrLxn4f9oVpR-k6vWA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4fkfkb9xVzedgBuIFoNThM4rJ-1Vda-7j5Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCERd7D4hNCgFL29iAihvvpKWLh4Gmu35kdQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0VQf8oMaTShZTNS7HGCdQH8W-QcL9bxrJJg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdaYZ1Dn1SXWYfEXS_BPaqkh-aV7bx3UFkig&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdaYZ1Dn1SXWYfEXS_BPaqkh-aV7bx3UFkig&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoRx9N7j0flwFMwB1Fch5x0s_WOxrh2AMINw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Udcbb4xsAhaLfjSDT24m2vkeEZyn8XLs7A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQdNX_rUkvo7Cg67441WW7ifAI4bRzYgPLsA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMQEgmqCq3-XI5UTQLauwiyK-Z8J-VVYoOgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTShyj7xOYwxa-qrp1Z4MxVqTkXk5faLZpsCw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcCL9njdTwbpAZjAu_BKPhzEbFdLQWeAlQ0Q&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQKbviKFo8-U13A4RVRdYOi2yCEHMe0nVPIg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgnAVIc2Qyqh9jC3Rl2tZax6NLE3FApskZPQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo50SY967Qc2ZWq-a6u902XeB2kO55VGQAIA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYvf8fqa0wTAOj4VRGzZVg_qk8ZGGjU13pOQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYoEbWHDm29LFyQGMUicW4ZKeVhbifj7IldA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdWlHHPJ78Lb2tW29iZel5Cj7SRUCYjG_dOQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkuT_ux-tsRBUocYrdk3MDhSmpXyofjy9MgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK_v3GWkgvcJO_4k2rJc4kWOKJI2HLwTGZbA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRrI3AL4lVk5gKonBIrztEPhQpTjcPn5ZdAQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8iKgtJNV063nb8wG6hLqMaFqxTIpf01_g-g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzC6LEmumQaFtUYGWkk9b3g-UcCY8jfELugg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyBHGTq7J6Er7E6taiJHaz6FID-8ryhBPc7g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4R5KDEosC0c1pl-rN6_ATI_5qsq8xSjhZkw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB4XecPwp0qb_uOFiKzyYxJuO4_QfynFtMNA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVVgfeG79S7WwGTO3WXzcJ2j_amrXkHykcRA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBJZ4Bt0qxNIvzk6MNQnTyTEhf6FlLDALSuQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjz9ombGj6JuXK44wbX3A2j1dSwMSAuXqkTw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkt0AyZgwSNVgyMRf9pAj-n5H68mQrgKEEvA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThrD-WpoqqGJc1Bjfi09YG4ASKHIQIHWA-WQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwB7HWaB1whZ9OwjMPPydpzFyx0dOLgbH82w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6bM55vXTt5zL7T7oWqH8UgQTF4qkzBERH-w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZMn1XeDgufVYJag0m1ScKyGvhZ-6VWlB4hA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJV3LrFkMhq69vJV8odiOJiKfm92RwO_kAOA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRovxdohY2NeB43U4u5yRj5RX67RKQd-PGgeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwDKmcso9ivQJhHAxJkQ90PfO6k8-E-Unz3A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPVWMdtX-WTsglvqyvxpdd_ncO6dZHKPhfWQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShZyvTIk_wX-RyFqVq6PsCVvQ43DzDg1gF0g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS18rjV61pf-Kkw93P8fo_GMD9Idv57BgQegA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVwk28fGpCeiOnU_v4gM_xmmutlD4TdTaJNIBnnakQuc9oBcMJBSFomlvD&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSF3B1t8IKJ8SackXZ34Ul844J8t89K_fraw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqt2QSj2E9P9E8qneWPqKN-Y9sTrRgFqgLeQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXGH0eM6A3qIBu1SoHO2WKLiYXCVits4u_Wg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnQ25QveaSQZK_fkdPwIWz8mifUYrUoBJnPA&s://linkat.in/Getmynumber',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY0nVbVAyDMiNgAOJSyFMdr9JgXP6u-tnRjg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPri27yFhlF-MAVeozZ00A-tp5r8oH4QZLQA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZtN2Z8Y0VCub7HXy1a1FNbkwA632bWbfQQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUgddTyJCjtmFXq-XYPADnuA_j2bhPr-iCFw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOzgVzG-UrcWB6i_pXRDZetIab4RVeGY6LfQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRig5Z4r9Na7WtvWMcPhMRWO-vxYITQxnGTEA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQBmNSSTyzY6qNUNXh3PWEO2voLlLDTFW6RA&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPWtvsoXkUSxr4FhGEWif36fdhmQ3WYrsaSA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGJdpCFIUFCozbAI1zxuOH8bdgzQ27mcg-zg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQah1H61b5BChnJoZkzH1VZ2ODQvOmYTMY71w&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEyWdR9JghLDjF8H1pjyQ1SrvpI7hMQD0jQA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUL6JxEUMLF9vvB2wq2-_VKmvUw1-eR3J49B4tiQBrj4tVz-_plQvabbE&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxFC7MTgJs5HxeKj5p-mCyMnIeoWx-PF8xV4buXfXiQwZ92G2fzioZicb1&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwRg4fw_NWyiGZcR8exPyuNNZLC5LspVCbQg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHhdSh1nBKZS8-Atw5Z6x4C4FrbAi5sC0Seg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQht92k0FECMx5KzD-8ry_UbRrXki2hAx2GZWxTnPwJGd1R8beor7qCFsua&s=10',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7Mjaz0O_EaQKNImm9POuvfhgpgACKgbHX5A&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfHc9wIUpAZ6tGgHcuh7uMgSE73e3MiXrpIw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSwa4h6ctjlKYAuYjTJg7apT7yFzeclZBCVw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLVSo425yfuohV1wofyHOHfSqGSqviMo3Ung&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSO6Bq9udLzcwFq-bJmd2B9Cq6oL9hMkZMuQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfMKZ1a1QxAhFHKbrcJTpbDX_qjWzlGbi5Rg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5So9rXG6_eILhT0bkgTqmiqo0Aa1kIGVr1g&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTczEUa2QtS5CvjAc9HFeZovoCLgtI1-Y5pYw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLZVsw3fF0MAcrvGRcjrocEyV3_cLkTVjZwA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeNWUV_8MU3wINXnyYHfrvEcYG-L-EYEraRw&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfa6rq74f35M30YTaKz0OUrCcIrTS5eCC_tg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7J6K9NBmnl8oEF8zMIy3mOwH4_xutpGAgKQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuSff_LbXojRUX_oE7waI3d3-QualApp3T7w&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXdfy8AVTJV2b4BQ4xisLXBpyeGu1oScXmg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScZS26U1UGiE2TlPDKUHLisbG4PJlyHg_jog&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnBczfXO7TJB2g9PXBFLz2wy69FOuh5mV7pg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSpWc12uRczAUU_zorKo-zqLhEeZDJITSmbA&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd9g4q6i8P29p9OF89IpJYDXFWxnUfT5nNgQ&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdeAXps2kgZGRgeulyGuYSEyLxLU44eFEUeg&usqp=CAU',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5PMHi_5Kl3X2ucjuo7D0KafekF10godIfMg&usqp=CAU'
];
